name: Java CI
on: push

env:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  DDL_AUTO: update
  DATABASE_URL: "jdbc:postgresql://postgres:postgres@localhost:5432/postgres"

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - run: mvn -B test
